# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: static-scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  static-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Veracode CLI
        run: curl -fsS https://tools.veracode.com/veracode-cli/install | sh
      - name: Auto packaging the application
        run: ./veracode package --source ${{ github.workspace }} --output ${{ github.workspace }}/docs/veracodeuploads --trust --debug
        env:
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_KEY }}

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ${{ github.workspace }}
    
      - name: Veracode Upload and Scan Action Step
        uses: veracode/veracode-uploadandscan-action@0.2.1
        id: upload_and_scan
        with:
          appname: 'AppSec Test'
          createprofile: false
          filepath: 'docs/veracodeuploads/**'
          version: '${{ github.run_id }}'
          vid: '3b9a9da91fe2e3365035749fb730ed17'
          vkey: '42788a675b96aa166d3bc8e6dd87417283c7256085f355089fb9f59a65ac2873e94fa0a842c6f12949c4c9b9223ffe7c4ca7dfd9378939ebdedc59b6d140227c'
          createsandbox: false
          sandboxname: 'Asit test'
          
