# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: static-scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
#permissions:
 # contents: read

jobs:
  static-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
         dotnet-version: '8.0'
      - name: Restore dependencies
        run: dotnet restore ${{ github.workspace }}
      - name: Build the application
        run: dotnet build --configuration debug -p:AllowUnsafeBlocks=true

      - name: Create temporary folder
        run: mkdir -p uploads
      - name: Download Veracode CLI
        run: curl -fsS https://tools.veracode.com/veracode-cli/install | sh
      - name: Auto packaging the .Net application
        run: ./veracode package --source ${{ github.workspace }} --output uploads --trust --debug
        env:
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_KEY }}
          
      - name: Checkout JavaScript repository
        uses: actions/checkout@v2
        with:
          repository: khan-sec/Javascript-demo-API
          token: ${{ secrets.REPO_PAT }}
          path: Javascript-demo-API
          
      - name: Auto packaging the JavaScript application
        run: ./veracode package --source Javascript-demo-API --output uploads --trust --debug
          


      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: uploads
    
      - name: Veracode Upload and Scan Action Step
        uses: veracode/veracode-uploadandscan-action@0.2.1
        id: upload_and_scan
        with:
          appname: 'AppSec Test'
          createprofile: false
          filepath: 'uploads/**'
          version: '${{ github.run_id }}'
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          createsandbox: false
          sandboxname: 'githubtest'
          
